# 网站信息
site_name: Hello World
site_url: https://book.wsfss.top
site_author: 风叔叔
site_description: >-
  风叔叔的分享

# 导航
nav:
  - 前言: index.md
  - 关于此书: about.md
  - 编程语言: 
    - Java:
      - 流处理与函数式编程: java/stream-function.md
      - 多线程: java/thread.md
      - 安全性: java/security.md
      - Lombok: java/lombok.md
  - 数据库:
    - MySQL: database/mysql.md
  - 开发技术:
    - Docker: technology/docker.md
    - Kubernetes: technology/kubernetes.md
    - Sealos K8s: technology/sealos.md
    - Jenkins: technology/jenkins.md
    - Maven: technology/maven.md
    - Git: technology/git.md
    - Spring: technology/spring.md
    - RocketMQ: technology/rocketmq.md
  - Mkdocs: 
    - 开始: mkdocs/start.md
    - 参考: mkdocs/reference.md
  - Blog:
    - blog/index.md

# 主题
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  # 右上角仓库图标
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default # 日间模式
      primary: white #导航背景
      accent: amber #强调色 如悬停、按钮
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black #导航背景
      accent: amber #强调色 如悬停、按钮
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  language: zh
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # - content.tabs.link #相同tab联动切换
    - content.tooltips
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.prune # 修剪功能，优化导航很多的场景页面加载速度
    - navigation.top # 返回顶部的按钮 在上滑时出现
    # - navigation.tabs.sticky # 滚动页面目录不隐藏
    # - navigation.expand #目录全部展开

repo_name: 258532431/mkdocs-book # github 仓库名称
repo_url: https://github.com/258532431/mkdocs-book.git # github 仓库
edit_uri: edit/main/docs/ # 编辑路径

# 版权
copyright: Copyright &copy; 2024 风叔叔

# Plugins
plugins:
  - macros
  - glightbox
  - blog:
      blog_toc: true # 显示目录
      post_excerpt_separator: <!-- more --> # 截取文章摘要标识
      archive: false # 是否开启归档
      # archive_name: Archive # 归档名称
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: false # 是否显示创建时间
  # - git-committers:
  #     repository: 258532431/mkdocs-book
  #     branch: main
  #     token: git token
  - git-authors
  - search:
      lang: zh

# Extra
extra:
  # generator: false  #删除页脚显示“使用MkDocs”
  social: # 页脚分享
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/
    - icon: fontawesome/brands/github
      link: https://github.com/trending
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/solid/paper-plane
      link: mailto:<258532431@qq.com>
      name: 258532431@qq.com
  # 网站统计
  analytics: 
    provider: google
    property: G-86QZVFJSKB
    feedback:
        title: 此页面有帮助吗？
        ratings:
          - icon: material/thumb-up-outline
            name: 此页面有帮助
            data: 1
            note: >-
              谢谢你的反馈！
          - icon: material/thumb-down-outline
            name: 此页面没有任何帮助
            data: 0
            note: >- 
              Thanks for your feedback! Help us improve this page by
              using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # 隐私政策
  consent:
    title: Cookie consent
    description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
      如果你同意，你可以帮助我们让我们的网站更好。

# markdown 扩展
markdown_extensions:
  - footnotes #脚注
  - admonition #提示
  - pymdownx.details #详情
  - pymdownx.superfences #代码块
  - pymdownx.highlight:
      anchor_linenums: true #行号
      linenums_style: pymdownx.inline
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite #代码高亮
  - pymdownx.snippets #代码片段
  - abbr #缩写
  - pymdownx.tabbed:
      alternate_style: true
  - tables #表格
  - pymdownx.critic #评论
  - pymdownx.caret #下划线
  - pymdownx.keys #键盘按键
  - pymdownx.mark #波浪线
  - pymdownx.tilde #删除线
  - attr_list #列表属性
  - md_in_html #html标签
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list #定义列表
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta #元数据

# extra_javascript:
  # - javascripts/extra.js
# extra_css:
  # - stylesheets/extra.css