apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs
  namespace: prod
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mkdocs
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      containers:
      - name: nginx
        image: sealos.hub:5000/mkdocs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        resources:
          limits:
            cpu: "0.5" # 限制分配的cpu核数
            memory: 256Mi # 限制分配的内存大小
          requests:
            cpu: "0.1"
            memory: 32Mi
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  namespace: prod
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mkdocs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mkdocs-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: book.wsfss.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mkdocs
            port:
              name: http
